service: bee

frameworkVersion: "3"

provider:
  name: aws
  region: ap-northeast-1
  ecr:
    images:
      appimage:
        path: ./
  environment:
    SLACK_CREDENTIALS_SECRET_ID: slack_secret_${sls:stage}
    DYNAMODB_TABLE: ${self:service}-${sls:stage}
    S3_BUCKET: ${self:service}-${sls:stage}
    ASSETS_PATH: https://${self:service}-${sls:stage}-assets.s3.${self:provider.region}.amazonaws.com/
  iamRoleStatements:
    - Effect: Allow
      Action:
        - secretsmanager:GetSecretValue
      Resource:
        - "*"
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - "*"
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
        - lambda:GetFunction
      Resource:
        - "*"

functions:
  app:
    image:
      name: appimage
    url: true
    events:
      - http:
          method: post
          path: /slack/events

plugins:
  - serverless-s3-sync
  - serverless-offline
  - serverless-dynamodb-local

custom:
  s3BucketName: ${self:provider.environment.DYNAMODB_TABLE}-assets
  s3Sync:
    - bucketName: ${self:custom.s3BucketName}
      localDir: assets/
  dynamodb:
    stages:
      - dev
    start:
      seed: true
    seed:
      development:
        sources:
          - table: ${self:provider.environment.DYNAMODB_TABLE}-review
            sources: [database/seed/review.json]
          - table: ${self:provider.environment.DYNAMODB_TABLE}-user
            sources: [database/seed/user.json]

resources: # CloudFormation template syntax from here on.
  Resources:
    BeeTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE}-review
        AttributeDefinitions:
          - AttributeName: user_id
            AttributeType: S
          - AttributeName: isbn
            AttributeType: S
        KeySchema:
          - AttributeName: user_id
            KeyType: HASH
          - AttributeName: isbn
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    UserTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE}-user
        AttributeDefinitions:
          - AttributeName: user_id
            AttributeType: S
        KeySchema:
          - AttributeName: user_id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    StaticSite:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.s3BucketName}
        AccessControl: PublicRead
    StaticSiteS3BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: StaticSite
        PolicyDocument:
          Statement:
            - Sid: PublicReadGetObject
              Effect: Allow
              Principal: "*"
              Action:
                - s3:GetObject
              Resource:
                Fn::Join: ["", ["arn:aws:s3:::", { "Ref": "StaticSite" }, "/*"]]
