// @ts-nocheck
// eslint-disable
// This file is generated by create-validator-ts
import Ajv from 'ajv';
import * as apiTypes from './review';

export const SCHEMA = {
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$ref": "#/definitions/Review",
    "definitions": {
        "Review": {
            "type": "object",
            "properties": {
                "userId": {
                    "type": "string"
                },
                "bookTitle": {
                    "type": "string"
                },
                "isbn": {
                    "type": "string"
                },
                "scoreForMe": {
                    "type": "string"
                },
                "scoreForOthers": {
                    "type": "string"
                },
                "reviewComment": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "bookImageUrl": {
                    "type": "string"
                },
                "bookAuthor": {
                    "type": "string"
                },
                "bookUrl": {
                    "type": "string"
                },
                "bookDescription": {
                    "type": "string"
                },
                "userName": {
                    "type": "string"
                }
            },
            "required": [
                "userId",
                "bookTitle",
                "isbn",
                "scoreForMe",
                "scoreForOthers",
                "reviewComment",
                "bookImageUrl",
                "bookAuthor",
                "bookUrl",
                "bookDescription"
            ],
            "additionalProperties": false
        }
    }
};
const ajv = new Ajv({ removeAdditional: true }).addSchema(SCHEMA, "SCHEMA");
export function validateReview(payload: unknown): apiTypes.Review {
  /** Schema is defined in {@link SCHEMA.definitions.Review } **/
  const validator = ajv.getSchema("SCHEMA#/definitions/Review");
  const valid = validator(payload);
  if (!valid) {
    const error = new Error('Invalid Review: ' + ajv.errorsText(validator.errors, {dataVar: "Review"}));
    error.name = "ValidationError";
    throw error;
  }
  return payload;
}

export function isReview(payload: unknown): payload is apiTypes.Review {
  try {
    validateReview(payload);
    return true;
  } catch (error) {
    return false;
  }
}
