name: Manual Deploy to production

on:
  workflow_dispatch:

deploy:
  uses: ./.github/workflows/deploy.yml
  with:
    stage: prod
  secrets:
    AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
    SLACK_WEBHOOK_URL: ${{ secrets.PR_MESSAGE_SLACK_WEBHOOK_URL }}
